# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements/development.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/espci_bar_web_app.py"
  - export FLASK_DEBUG=1
  - export SECRET_KEY='notsosecret'

script:
  - py.test --cov=app tests/
  - coverage report -m

after_success:
  - coveralls
