# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r requirements/development.txt
  - pip install tox-travis
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/espci_bar_web_app.py"
  - export FLASK_DEBUG=1

script:
  - tox
  - coverage run -m py.test
  - coverage report -m

after_success:
  - coveralls
